# Generated by Django 2.2 on 2019-05-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgendainvites',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eventinvites',
            name='status',
        ),
    ]
