# Generated by Django 2.2 on 2019-05-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190511_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgendainvites',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinvites',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
