# Generated by Django 2.2 on 2019-05-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190511_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgendainvites',
            name='adg_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adgendainvites',
            name='invite_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinvites',
            name='event_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
