# Generated by Django 2.2 on 2019-05-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImageModel',
        ),
    ]
