# Generated by Django 2.2 on 2019-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_uploadimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
