# Generated by Django 2.2 on 2019-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_uploadimg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimg',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
