# Generated by Django 2.2 on 2019-05-12 14:31

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190511_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.ien_media),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/profile'),
        ),
    ]
