# Generated by Django 2.2 on 2019-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190522_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/marketP')),
                ('event_id', models.ForeignKey(on_delete=True, to='myapp.Event')),
            ],
            options={
                'verbose_name': 'event_picture',
            },
        ),
    ]
