# Generated by Django 2.2 on 2019-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_eventpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/event'),
        ),
        migrations.CreateModel(
            name='MarketPlacePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/marketP')),
                ('market_place_id', models.ForeignKey(on_delete=True, to='myapp.MarketPlace')),
            ],
            options={
                'verbose_name': 'market_place_picture',
            },
        ),
    ]
