# Generated by Django 2.0.3 on 2019-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190528_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgenda',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adgenda',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marketplacepictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/media/marketP'),
        ),
    ]
