# Generated by Django 2.0.3 on 2019-07-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190704_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgenda',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
