# Generated by Django 2.0.3 on 2019-07-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190705_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacepictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/market-place'),
        ),
    ]
